name: Build PolyRhythmMetronome APK

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Buildozer command"
        type: choice
        required: true
        default: android debug
        options: [android debug, android release, android release aab]
      spec_path:
        description: "Path to buildozer.spec"
        type: string
        required: true
        default: ./PolyRhythmMetronome/android/buildozer.spec
      clean:
        description: "Clean before build?"
        type: boolean
        default: false
      create_release:
        description: "Create a GitHub Release after build?"
        type: boolean
        default: false

permissions:
  contents: write

concurrency:
  group: build-android-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create cache dirs as root, then give them back to the runner user.
      - name: Prep cache dirs (no chown to 'user')
        run: |
          sudo mkdir -p "${HOME}/.buildozer" ".buildozer" "bin"
          sudo chown -R "$USER:$USER" "${HOME}/.buildozer" ".buildozer" "bin"

      - name: Cache global .buildozer
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: global-buildozer-${{ runner.os }}-${{ hashFiles(inputs.spec_path) }}

      - name: Cache project .buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: proj-buildozer-${{ runner.os }}-${{ hashFiles(inputs.spec_path) }}

      - name: Optional clean
        if: ${{ fromJson(inputs.clean) }}
        run: |
          buildozer android clean || true
          rm -rf .buildozer bin || true
          mkdir -p .buildozer bin

      - name: Build with Buildozer
        id: build
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: ./PolyRhythmMetronome/android
          command: ${{ inputs.target }}

      - name: Upload artifacts (APK/AAB)
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            PolyRhythmMetronome/android/bin/*.apk
            PolyRhythmMetronome/android/bin/*.aab
          if-no-files-found: warn

      - name: Create GitHub Release (optional)
        if: ${{ fromJson(inputs.create_release) }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Android build ${{ github.run_number }}
          files: |
            PolyRhythmMetronome/android/bin/*.apk
            PolyRhythmMetronome/android/bin/*.aab
