name: Build PolyRhythmMetronome APK

# This workflow builds the PolyRhythmMetronome Android APK and stores it as GitHub Artifacts and Releases.
# Built APKs are available via:
# 1. Artifacts section (30 days retention)
# 2. Releases section (permanent, main branch builds only)

permissions:
  contents: write
  packages: write

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'PolyRhythmMetronome/android/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'PolyRhythmMetronome/android/**'
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a release after build'
        required: false
        default: false
        type: boolean

jobs:
  build-polyrhythm-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for potential version calculation
    
    - name: Free disk space
      run: |
        echo "Freeing up disk space for Android build..."
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h
    
    - name: Build APK with Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1.2.0
      id: buildozer
      with:
        workdir: PolyRhythmMetronome/android
        buildozer_version: stable
    
    - name: Verify APK build
      run: |
        echo "✅ Buildozer action completed successfully"
        echo "APK filename: ${{ steps.buildozer.outputs.filename }}"
        if [ -f "${{ steps.buildozer.outputs.filename }}" ]; then
          echo "✅ APK file verified"
          ls -lh "${{ steps.buildozer.outputs.filename }}"
        else
          echo "❌ APK file not found at expected location"
          exit 1
        fi
    
    - name: Get APK info
      id: apk_info
      run: |
        APK_PATH="${{ steps.buildozer.outputs.filename }}"
        APK_NAME=$(basename "$APK_PATH")
        echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
        echo "APK Name: $APK_NAME"
        echo "APK Path: $APK_PATH"
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: polyrhythm-metronome-apk
        path: ${{ steps.buildozer.outputs.filename }}
        retention-days: 30
    
    - name: Create Release (if requested or on main branch)
      if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && inputs.create_release == 'true')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: polyrhythm-metronome-android-${{ github.run_number }}
        name: PolyRhythmMetronome Android v1.0-build${{ github.run_number }}
        body: |
          # PolyRhythmMetronome Android APK
          
          Automated build of PolyRhythmMetronome Android application.
          
          ## Downloads
          - **Android APK**: ${{ steps.apk_info.outputs.apk_name }}
          
          ## Installation
          1. Download the APK file
          2. Transfer it to your Android device
          3. Enable "Install from Unknown Sources" in Settings
          4. Tap the APK file to install
          
          ## Build Information
          - Build: ${{ github.run_number }}
          - Commit: ${{ github.sha }}
          - Workflow: ${{ github.workflow }}
          
          ## Compatibility
          - Minimum Android: 5.0 (API 21)
          - Target Android: 12 (API 31)
          - Architectures: arm64-v8a, armeabi-v7a
          
          ## Features
          - Multi-layer rhythm patterns
          - Stereo subdivision metronome
          - Custom drum sounds and tone generation
          - Real-time rhythm editing
          - Save/load rhythm patterns
          
          For more information, see the [PolyRhythmMetronome documentation](https://github.com/TheMikaus/BandTools/tree/main/PolyRhythmMetronome/android).
        files: |
          ${{ steps.apk_info.outputs.apk_path }}
        draft: false
        prerelease: false
